package com.volunteerflow.activity;
import com.baomidou.mybatisplus.core.toolkit.IdWorker; import com.volunteerflow.audit.AuditService; import com.volunteerflow.infrastructure.web.BusinessException; import com.volunteerflow.rbac.OrganizationAuthorizationService; import org.springframework.context.annotation.Profile; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.List;
@Service @Profile("!test") public class ActivityService {
 private final ActivityMapper activities; private final ActivityPositionMapper positions; private final OrganizationAuthorizationService authorization; private final AuditService audit; private final Clock clock;
 public ActivityService(ActivityMapper a,ActivityPositionMapper p,OrganizationAuthorizationService z,AuditService u,Clock c){activities=a;positions=p;authorization=z;audit=u;clock=c;}
 @Transactional public Activity create(Long userId,Long orgId,ActivityRequest r){authorization.requirePermission(userId,orgId,"activity:create"); validateTimes(r); Activity a=new Activity();a.setId(IdWorker.getId());a.setOrganizationId(orgId);apply(a,r);a.setStatus("DRAFT");a.setCreatedBy(userId);a.setVersion(0);activities.insert(a);audit.record(orgId,userId,"activity.created","activity",a.getId(),null);return a;}
 @Transactional public Activity update(Long userId,Long id,ActivityRequest r){Activity a=required(id);authorization.requirePermission(userId,a.getOrganizationId(),"activity:create");if(!"DRAFT".equals(a.getStatus()))throw conflict("ACTIVITY_NOT_DRAFT","Only draft activities can be directly edited");validateTimes(r);apply(a,r);activities.updateById(a);audit.record(a.getOrganizationId(),userId,"activity.updated","activity",id,null);return a;}
 @Transactional public ActivityPosition addPosition(Long userId,Long activityId,PositionRequest r){Activity a=required(activityId);authorization.requirePermission(userId,a.getOrganizationId(),"activity:create");if(!"DRAFT".equals(a.getStatus()))throw conflict("ACTIVITY_NOT_DRAFT","Positions can only be added directly to drafts"); boolean oneTimeMissing=(r.serviceStartAt()==null)!=(r.serviceEndAt()==null); if(oneTimeMissing||(r.serviceStartAt()!=null&&!r.serviceStartAt().isBefore(r.serviceEndAt())))throw semantic("INVALID_POSITION_TIME","Position service times must be a valid start/end pair"); ActivityPosition p=new ActivityPosition();p.setId(IdWorker.getId());p.setOrganizationId(a.getOrganizationId());p.setActivityId(a.getId());p.setName(r.name().trim());p.setDescription(r.description().trim());p.setCapacity(r.capacity());p.setRegistrationMode(r.registrationMode());p.setPromotionTimeoutMinutes(r.promotionTimeoutMinutes()==null?120:r.promotionTimeoutMinutes());p.setServiceStartAt(r.serviceStartAt());p.setServiceEndAt(r.serviceEndAt());p.setMeetingLocation(trim(r.meetingLocation()));p.setNextWaitlistSequence(1L);p.setStatus("ACTIVE");p.setVersion(0);positions.insert(p);audit.record(a.getOrganizationId(),userId,"activity.position.created","activity_position",p.getId(),null);return p;}
 @Transactional public Activity publish(Long userId,Long id){Activity a=required(id);authorization.requirePermission(userId,a.getOrganizationId(),"activity:publish");if(!"DRAFT".equals(a.getStatus()))throw conflict("ACTIVITY_NOT_DRAFT","Only draft activities can be published");validate(a);if(positions.countActiveByActivity(a.getOrganizationId(),id)<1)throw semantic("ACTIVITY_POSITION_REQUIRED","At least one active position is required");a.setStatus("PUBLISHED");a.setPublishedAt(now());activities.updateById(a);audit.record(a.getOrganizationId(),userId,"activity.published","activity",id,null);return a;}
 @Transactional public Activity cancel(Long userId,Long id,String reason){Activity a=required(id);authorization.requirePermission(userId,a.getOrganizationId(),"activity:cancel");if("CANCELED".equals(a.getStatus())||"FINISHED".equals(a.getStatus()))throw conflict("ACTIVITY_FINAL","Activity is already final");a.setStatus("CANCELED");a.setCanceledAt(now());activities.updateById(a);audit.record(a.getOrganizationId(),userId,"activity.canceled","activity",id,reason);return a;}
 public List<ActivitySummary> list(Long userId,Long orgId){authorization.requireMembership(userId,orgId);return activities.selectPublished(orgId).stream().map(a->new ActivitySummary(a,positions.selectActiveByActivity(orgId,a.getId()))).toList();}
 public ActivityDetail detail(Long userId,Long id){Activity a=required(id);authorization.requireMembership(userId,a.getOrganizationId());if(!"PUBLISHED".equals(a.getStatus()))authorization.requirePermission(userId,a.getOrganizationId(),"activity:read");return new ActivityDetail(a,positions.selectActiveByActivity(a.getOrganizationId(),id));}
 private Activity required(Long id){Activity a=activities.selectById(id);if(a==null)throw new BusinessException(HttpStatus.NOT_FOUND,"ACTIVITY_NOT_FOUND","Activity was not found");return a;} private LocalDateTime now(){return LocalDateTime.ofInstant(clock.instant(),ZoneOffset.UTC);} private String trim(String v){return v==null?null:v.trim();}
 private void apply(Activity a,ActivityRequest r){a.setTitle(r.title().trim());a.setDescription(r.description().trim());a.setLocation(r.location().trim());a.setRegistrationStartAt(r.registrationStartAt());a.setRegistrationEndAt(r.registrationEndAt());a.setFreeCancelDeadlineAt(r.freeCancelDeadlineAt());a.setActivityStartAt(r.activityStartAt());a.setActivityEndAt(r.activityEndAt());}
 private void validateTimes(ActivityRequest r){if(!r.registrationStartAt().isBefore(r.registrationEndAt())||!r.registrationEndAt().isBefore(r.activityStartAt())||!r.activityStartAt().isBefore(r.activityEndAt())||(r.freeCancelDeadlineAt()!=null&&r.freeCancelDeadlineAt().isAfter(r.activityStartAt())))throw semantic("INVALID_ACTIVITY_TIME","Activity time ordering is invalid");}
 private void validate(Activity a){if(!a.getRegistrationStartAt().isBefore(a.getRegistrationEndAt())||!a.getRegistrationEndAt().isBefore(a.getActivityStartAt())||!a.getActivityStartAt().isBefore(a.getActivityEndAt()))throw semantic("INVALID_ACTIVITY_TIME","Activity time ordering is invalid");}
 private BusinessException semantic(String code,String msg){return new BusinessException(HttpStatus.UNPROCESSABLE_ENTITY,code,msg);} private BusinessException conflict(String code,String msg){return new BusinessException(HttpStatus.CONFLICT,code,msg);}
 public record ActivityRequest(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=160) String title,@jakarta.validation.constraints.NotBlank String description,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=255) String location,@jakarta.validation.constraints.NotNull LocalDateTime registrationStartAt,@jakarta.validation.constraints.NotNull LocalDateTime registrationEndAt,LocalDateTime freeCancelDeadlineAt,@jakarta.validation.constraints.NotNull LocalDateTime activityStartAt,@jakarta.validation.constraints.NotNull LocalDateTime activityEndAt){}
 public record PositionRequest(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=128) String name,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=1000) String description,@jakarta.validation.constraints.Min(1) int capacity,@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Pattern(regexp="FIRST_COME|REVIEW") String registrationMode,@jakarta.validation.constraints.Min(30) @jakarta.validation.constraints.Max(720) Integer promotionTimeoutMinutes,LocalDateTime serviceStartAt,LocalDateTime serviceEndAt,@jakarta.validation.constraints.Size(max=255) String meetingLocation){}
 public record ActivitySummary(Activity activity,List<ActivityPosition> positions){} public record ActivityDetail(Activity activity,List<ActivityPosition> positions){} public record CancelRequest(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=500) String reason){}
}
