package com.volunteerflow.organization;
import com.volunteerflow.auth.CurrentUser; import com.volunteerflow.infrastructure.web.ApiResponse; import jakarta.validation.Valid; import org.springframework.context.annotation.Profile; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController @Profile("!test") @RequestMapping("/api/v1") public class OrganizationController {
 private final OrganizationService service; public OrganizationController(OrganizationService s){service=s;}
 @PostMapping("/organizations") public ResponseEntity<ApiResponse<Organization>> create(@AuthenticationPrincipal CurrentUser u,@Valid @RequestBody OrganizationService.CreateOrganizationRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.of(service.create(u.id(),u.platformRole(),r)));}
 @GetMapping("/organizations") public ApiResponse<List<Organization>> list(@AuthenticationPrincipal CurrentUser u){return ApiResponse.of(service.list(u.id(),u.platformRole()));}
 @GetMapping("/organizations/{id}") public ApiResponse<Organization> get(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id){return ApiResponse.of(service.get(u.id(),u.platformRole(),id));}
 @PostMapping("/organizations/{id}/deactivation") public ResponseEntity<Void> deactivate(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id){service.deactivateOrganization(u.id(),u.platformRole(),id);return ResponseEntity.noContent().build();}
 @PostMapping("/organizations/{id}/invitations") public ResponseEntity<ApiResponse<InviteCode>> invite(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@Valid @RequestBody CreateInviteRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.of(service.createInvite(u.id(),id,r)));}
 @PostMapping("/organization-memberships") public ResponseEntity<ApiResponse<OrganizationMember>> join(@AuthenticationPrincipal CurrentUser u,@Valid @RequestBody JoinRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.of(service.joinByInvite(u.id(),r.code())));}
 @PostMapping("/organizations/{id}/invitations/{inviteId}/deactivation") public ResponseEntity<Void> deactivateInvite(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@PathVariable Long inviteId){service.deactivateInvite(u.id(),id,inviteId);return ResponseEntity.noContent().build();}
 @GetMapping("/organizations/{id}/members") public ApiResponse<List<OrganizationMember>> members(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id){return ApiResponse.of(service.members(u.id(),id));}
 @PatchMapping("/organizations/{id}/members/{memberId}/role") public ApiResponse<OrganizationMember> assign(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@PathVariable Long memberId,@Valid @RequestBody OrganizationService.AssignRoleRequest r){return ApiResponse.of(service.assignRole(u.id(),id,memberId,r));}
 @GetMapping("/organizations/{id}/roles") public ApiResponse<List<com.volunteerflow.rbac.RbacRole>> roles(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id){return ApiResponse.of(service.roles(u.id(),id));}
 @GetMapping("/organizations/{id}/permissions") public ApiResponse<List<com.volunteerflow.rbac.RbacPermission>> permissions(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id){return ApiResponse.of(service.permissions(u.id(),id));}
 @PostMapping("/organizations/{id}/roles") public ResponseEntity<ApiResponse<com.volunteerflow.rbac.RbacRole>> role(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@Valid @RequestBody OrganizationService.CreateRoleRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.of(service.createRole(u.id(),id,r)));}
 @PutMapping("/organizations/{id}/roles/{roleId}/permissions") public ResponseEntity<Void> permissions(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@PathVariable Long roleId,@Valid @RequestBody OrganizationService.SetRolePermissionsRequest r){service.setRolePermissions(u.id(),id,roleId,r);return ResponseEntity.noContent().build();}
 @PutMapping("/organizations/{id}/roles/{roleId}") public ApiResponse<com.volunteerflow.rbac.RbacRole> updateRole(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@PathVariable Long roleId,@Valid @RequestBody OrganizationService.UpdateRoleRequest r){return ApiResponse.of(service.updateRole(u.id(),id,roleId,r));}
 @PostMapping("/organizations/{id}/roles/{roleId}/deactivation") public ResponseEntity<Void> deactivateRole(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@PathVariable Long roleId){service.deactivateRole(u.id(),id,roleId);return ResponseEntity.noContent().build();}
 @DeleteMapping("/organizations/{id}/roles/{roleId}") public ResponseEntity<Void> deleteRole(@AuthenticationPrincipal CurrentUser u,@PathVariable Long id,@PathVariable Long roleId){service.deleteRole(u.id(),id,roleId);return ResponseEntity.noContent().build();}
 public record JoinRequest(@jakarta.validation.constraints.NotBlank String code){}
}
